openapi: "3.1.0"
info:
  title: "ao_oppfolgingskontor API"
  description: "ao_oppfolgingskontor API"
  version: "1.0.0"
servers:
  - url: "https://ao_oppfolgingskontor"
paths:
  /api/kontor:
    post:
      description: "Tilordne arbeidsoppfolgings-kontor til en bruker. Andre kontortyper kan ikke tilordnes manuelt."
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/ArbeidsoppfolgingsKontorTilordningDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "OK"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Kunne ikke oppdatere kontor"
components:
  schemas:
    ArbeidsoppfolgingsKontorTilordningDTO:
      type: "object"
      properties:
        kontorId:
          type: "string"
        fnr:
          type: "string"
      required:
        - "kontorId"
        - "fnr"