package kafka.consumers.oppfolgingsHendelser

enum class OppfolgingStartBegrunnelse {
    ARBEIDSSOKER_REGISTRERING,
    ARENA_SYNC_ARBS,
    ARENA_SYNC_IARBS,
    REAKTIVERT_OPPFØLGING,
    MANUELL_REGISTRERING_BRUKER,
    MANUELL_REGISTRERING_VEILEDER,
    SYKMELDT_UTEN_ARBEIDSGIVER_4_UKER;
}
