appName: "$NAIS_APP_NAME"

ktor:
    application:
        modules:
            - no.nav.ApplicationKt.module
    deployment:
        port: 8080

auth:
  entraIssuer: "$AZURE_OPENID_CONFIG_ISSUER"
  naisTokenExchangeEndpoint: "$NAIS_TOKEN_EXCHANGE_ENDPOINT"

no:
  nav:
    security:
      jwt:
        issuers:
          - issuer_name: "$AZURE_OPENID_CONFIG_ISSUER"
            discoveryurl: "$AZURE_APP_WELL_KNOWN_URL"
            accepted_audience: "$AZURE_APP_CLIENT_ID"

apis:
  norg2:
    url: "$NORG2_URL"
  poaoTilgang:
    url: "$POAO_TILGANG_URL"
  pdl:
    url: "$PDL_URL"
  arbeidssokerregisteret:
    url: "$ARBEIDSSOKERREGISTERET_URL"
    scope: "$ARBEIDSSOKERREGISTERET_SCOPE"


postgres:
  host: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_HOST"
  port: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_PORT"
  database-name: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_DATABASE"
  user: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_USERNAME"
  password: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_PASSWORD"
  ssl-root-cert: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_SSLROOTCERT"
  ssl-mode: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_SSLMODE"
  ssl-cert: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_SSLCERT"
  jdbc-url: "$NAIS_DATABASE_AO_OPPFOLGINGSKONTOR_AO_OPPFOLGINGSKONTOR_JDBC_URL"

kafka:
  application-id: "$KAFKA_STREAMS_APPLICATION_ID"
  brokers: "$KAFKA_BROKERS"
  schema-registry: "$KAFKA_SCHEMA_REGISTRY"
  schema-registry-user: "$KAFKA_SCHEMA_REGISTRY_USER"
  schema-registry-password: "$KAFKA_SCHEMA_REGISTRY_PASSWORD"
  certificate: "$KAFKA_CERTIFICATE"
  certificate-path: "$KAFKA_CERTIFICATE_PATH"
  private-key: "$KAFKA_PRIVATE_KEY"
  private-key-path: "$KAFKA_PRIVATE_KEY_PATH"
  ca: "$KAFKA_CA"
  ca-path: "$KAFKA_CA_PATH"
  credstore-password: "$KAFKA_CREDSTORE_PASSWORD"
  keystore-path: "$KAFKA_KEYSTORE_PATH"
  truststore-path: "$KAFKA_TRUSTSTORE_PATH"


topics:
  inn:
    endringPaOppfolgingsbruker: "pto.endring-paa-oppfolgingsbruker-v2"
    oppfolgingsperiodeTopic=pto: "pto.oppfolgingsperiode-v1"
