ktor:
    application:
        modules:
            - no.nav.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: passwordjwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

kafka:
  brokers: "$KAFKA_BROKERS"
  schema-registry: "$KAFKA_SCHEMA_REGISTRY"
  schema-registry-user: "$KAFKA_SCHEMA_REGISTRY_USER"
  schema-registry-password: "$KAFKA_SCHEMA_REGISTRY_PASSWORD"
  certificate: "$KAFKA_CERTIFICATE"
  certificate-path: "$KAFKA_CERTIFICATE_PATH"
  private-key: "$KAFKA_PRIVATE_KEY"
  private-key-path: "$KAFKA_PRIVATE_KEY_PATH"
  ca: "$KAFKA_CA"
  ca-path: "$KAFKA_CA_PATH"
  credstore-password: "$KAFKA_CREDSTORE_PASSWORD"
  keystore-path: "$KAFKA_KEYSTORE_PATH"
  truststore-path: "$KAFKA_TRUSTSTORE_PATH"
  secret-updated: "$AIVEN_SECRET_UPDATED"