apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ao-oppfolgingskontor-kafka-streams-rules
  namespace: dab
  labels:
    team: dab
spec:
  groups:
    - name: KafkaStreamsHelse
      rules:
        - alert: KafkaStreamsPodDown
          # Logikk: For en gitt pod (gruppert på pod-label), finnes det en prosess-metrikk,
          # MEN det finnes IKKE en kafka-metrikk?
          expr: |
            (
              count by (pod) (process_uptime_seconds{app="ao-oppfolgingskontor"}) > 0
            )
            AND ON (pod)
            (
              count by (pod) (kafka_stream_alive_stream_threads{app="ao-oppfolgingskontor"}) == 0
            )
          for: 5m
          annotations:
            consequence: "Kafka Streams-klienten har sannsynligvis krasjet i pod `{{ $labels.pod }}`."
            action: "Undersøk logger for den spesifikke podden: `kubectl logs {{ $labels.pod }} -n dab`"
            summary: "Pod `{{ $labels.pod }}` rapporterer at den kjører, men dens Kafka Streams-metrikker har forsvunnet."
          labels:
            namespace: dab
            severity: critical
        - alert: AllKafkaStreamsDown
          # Logikk: Antall poder som rapporterer prosess-uptime er større enn 0,
          # MEN antall poder som rapporterer kafka-uptime er nøyaktig 0.
          expr: |
            (
              count(process_uptime_seconds{app="ao-oppfolgingskontor"}) > 0
            )
            AND
            (
              count(kafka_stream_alive_stream_threads{app="ao-oppfolgingskontor"}) == 0
            )
          for: 5m
          annotations:
            consequence: "Kafka Streams har krasjet i ALLE poder for applikasjonen `{{ $labels.app }}`."
            action: "Dette er en total tjenestesvikt for meldingsprosessering. Start en feilsøking på tvers av hele deployeringen."
            summary: "Ingen av podene for `{{ $labels.app }}` rapporterer lenger Kafka Streams-metrikker, selv om podene ser ut til å kjøre."
          labels:
            namespace: dab
            severity: critical