apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ao-oppfolgingskontor-kafka-streams-rules
  namespace: dab
  labels:
    team: dab
spec:
  groups:
    - name: KafkaStreamsHelse
      rules:
        - alert: KafkaStreamsKlientErNede
          expr: |
            kafka_streams_application_state{app="ao-oppfolgingskontor"} == 0
          for: 2m
          annotations:
            consequence: "Kafka Streams-klienten har feilet og er ikke i RUNNING-tilstand."
            action: "Streams app '{{ $labels.streams_application_id }}' i pod '{{ $labels.pod }}' har status 0. Sjekk logger for denne podden: `kubectl logs {{ $labels.pod }} -n dab`"
          labels:
            namespace: dab
            severity: critical
        - alert: KafkaStreamsStuckRebalancing
          expr: |
            kafka_streams_application_state{app="ao-oppfolgingskontor"} == 2
          for: 15m # Gi den god tid til å rebalansere normalt
          annotations:
            consequence: "Kafka Streams-klienten '{{ $labels.streams_application_id }}' har vært i REBALANCING-tilstand (status 2) i over 15 minutter."
            action: "Undersøk om det er problemer med tilkobling til Kafka-clusteret, eller om det er en 'rebalance storm'. Sjekk logger for denne podden: `kubectl logs {{ $labels.pod }} -n dab`"
            summary: "Vedvarende rebalancing i Kafka Streams-klienten"
          labels:
            namespace: dab
            severity: warning
        - alert: EldreFeiledeMeldinger
          expr: |
            max_over_time(
              max by (app) (
                kafka_retry_processor_failed_messages_older_than_20_minutes{app="ao-oppfolgingskontor"}
              )[10m]
            ) > 0
          for: 5m
          annotations:
            consequence: "Det finnes en person under oppfølging som ikke vil få tildelt arbeidsoppfølgingskontor"
            action: "Undersøk årsaken til dette og gjør nødvendige endringer."
            summary: "Det finnes én eller flere feilede meldinger som er eldre enn 20 minutter i ao-oppfolgingskontor."
          labels:
            namespace: dab
            severity: critical