kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: ao-oppfolgingskontor
  namespace: dab
  labels:
    team: dab
spec:
  ingresses:
    - https://ao-oppfolgingskontor.intern.nav.no
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
