kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: ao-oppfolgingskontor
  namespace: dab
  labels:
    team: dab
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  ingresses:
    - https://ao-oppfolgingskontor.intern.nav.no
  port: 8080
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskType: SSD
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: ao-oppfolgingskontor
            users:
              - name: datastream
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 768m
      memory: 864Mi
  kafka:
    pool: nav-prod
    streams: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
        - application: poao-admin
          namespace: poao
          permissions:
            scopes:
              - "admin"
        - application: populasjonstilgangskontroll
          namespace: tilgangsmaskin
          permissions:
           roles:
             - "bulk-hent-kontor"
    outbound:
      rules:
        - application: norg2
          namespace: org
        - application: poao-tilgang
          namespace: poao
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
          namespace: paw
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: norg2.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: veilarbarena.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  env:
    - name: AAREG_URL
      value: https://aareg-services.intern.nav.no
    - name: NORG2_URL
      value: http://norg2.org
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: ARBEIDSSOKERREGISTERET_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag-v2.paw
    - name: ARBEIDSSOKERREGISTERET_SCOPE
      value: api://prod-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag-v2/.default
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: http://skjermede-personer-pip.nom
    - name: SKJERMEDE_PERSONER_PIP_SCOPE
      value: api://prod-gcp.nom.skjermede-personer-pip/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.prod-fss-pub.nais.io
    - name: VEILARBARENA_SCOPE
      value: api://prod-fss.pto.veilarbarena/.default
