kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: ao-oppfolgingskontor
  namespace: dab
  labels:
    team: dab
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  ingresses:
    - https://ao-oppfolgingskontor.intern.dev.nav.no
  port: 8080
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: ao-oppfolgingskontor
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 672Mi
    requests:
      cpu: 851m
      memory: 640Mi
  kafka:
    pool: nav-dev
    streams: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
        - application: poao-admin
          namespace: poao
          permissions:
            scopes:
              - "republiser-kontor"
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
          permissions:
            roles:
              - "bulk-hent-kontor"
            scopes:
              - "republiser-kontor"
        - application: populasjonstilgangskontroll
          namespace: tilgangsmaskin
          permissions:
            roles:
              - "bulk-hent-kontor"
    outbound:
      rules:
        - application: norg2
          namespace: org
        - application: poao-tilgang
          namespace: poao
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
          namespace: paw
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: norg2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  env:
    - name: NORG2_URL
      value: http://norg2.org
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: ARBEIDSSOKERREGISTERET_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag-v2.paw
    - name: ARBEIDSSOKERREGISTERET_SCOPE
      value: api://dev-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag-v2/.default
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: http://skjermede-personer-pip.nom
    - name: SKJERMEDE_PERSONER_PIP_SCOPE
      value: api://dev-gcp.nom.skjermede-personer-pip/.default
