name: build.yml
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true
    outputs:
      image:
        description: "Image name pushed to GAR"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.1.0"
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Test and build
        run: ./gradlew build --scan

      - name: Generate graphql schema
        run: ./gradlew graphqlGenerateSDL

      - name: Generate and output SBOM
        uses: anchore/sbom-action@v0

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          docker_context: .
          team: dab
          byosbom: 'build/reports/bom.json'
      - name: Slack Notification (test failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'ao-oppfolgingskontor: tester feilet under bygg'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Commit-message til feilende deploy: ${{ github.event.head_commit.message }}'
