name: Deploy feature branch to dev
run-name:  Deploy feature branch ${{ github.ref_name }} to dev by @${{ github.actor }}

on:
  workflow_dispatch:

concurrency:
  group: deploy-feature
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env: dev