name: Deploy main branch
run-name:  Deploy main branch by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TZ: Europe/Oslo

concurrency:
  group: deploy-main
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy-dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env: dev

  deploy-prod:
    name: Deploy to prod
    needs: [deploy-dev]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env: prod